---
- template: src=resolv.conf.j2 dest=/etc/resolv.conf
- yum: name={{item}} state=latest
  with_items:
    - wget
    - git
    - net-tools
    - bind-utils
    - iptables-services
    - bridge-utils
    - bash-completion
    - docker
- copy: src=docker.service dest=/usr/lib/systemd/system/docker.service
# - file: dest=/usr/bin/docker src=/usr/bin/docker-current state=hard
- template: src=docker.j2 dest=/etc/sysconfig/docker
- service: name=docker state=restarted enabled=yes
- command: docker-storage-setup
- iptables: action=insert chain=INPUT jump=OS_FIREWALL_ALLOW
- iptables: action=append chain=OS_FIREWALL_ALLOW protocol=tcp match=tcp destination_port=80 source_port=80 jump=ACCEPT
- iptables: action=append chain=OS_FIREWALL_ALLOW protocol=tcp match=tcp destination_port=10250 source_port=10250 jump=ACCEPT
- iptables: action=append chain=OS_FIREWALL_ALLOW protocol=tcp match=tcp destination_port=443 source_port=443 jump=ACCEPT
