name: devops
root: ./

pre_window: export DOCKER_HOST=tcp://10.1.2.2:2376

startup_window: base

windows:
  - base: echo "Root of project"
#  - build.system:
#      root: ./build-system
#      panes:
#        - vagrant status
#  - head.ui:
#      root: ./head-ui
#      panes:
#        - git status
