---
- hosts: infra
  become: true
  tasks:
    - yum: pkg=* state=latest
    - yum: pkg=java-1.8.0-openjdk state=latest
    - user: name=nexus
    - get_url: url=https://sonatype-download.global.ssl.fastly.net/nexus/3/nexus-3.0.0-03-unix.tar.gz dest=/opt
    - unarchive: src=/opt/nexus-3.0.0-03-unix.tar.gz dest=/opt owner=nexus group=nexus copy=no
    - file: src=/opt/nexus-3.0.0-03/bin/nexus dest=/usr/local/bin/nexus state=link
    - copy: src=nexus.service dest=/etc/systemd/system/
    - service: name=nexus.service state=restarted enabled=yes
    - firewalld: port=80/tcp permanent=true state=enabled
    - yum: pkg=mariadb-server state=latest
    - service: name=mariadb-server state=started enabled=yes
    - mysql_user:
        name: root
        password: "{{ mysql_password }}"
        host: localhost
    - mysql_db: name=gogs
    - rpm_key:
        state: present
        key: "https://rpm.packager.io/key"
    - copy: src=gogs.repo dest=/etc/yum.repos.d
    - yum: pkg=gogs state=latest
    - yum: pkg=nginx state=latest
    - copy: src=gogs-nginx.conf dest=/etc/nginx/conf.d/gogs.conf
    - copy: src=nexus-nginx.conf dest=/etc/nginx/conf.d/nexus.conf
    - service: name=nginx state=restarted enabled=yes
